### ISSUE TITLE
Tasks for next week

### ISSUE THREAD

**Issue by davidgolub** [StanfordCS194/Team-14#3]
Summary of what everyone agreed on today:
1) Decide on project
2) Competitive landscape analysis
3) Decide on roles
4) Design tech stack

Reach goal: Mockups/code

Good luck!

**Comment by JBB** [comment]
Course planning aid for your reference:
[The Ultimate Stanford Course Planner](https://docs.google.com/spreadsheets/d/1sdC4UDqVDEZj82a9Jjf3JI67l6ZD62QjQ93H5nqA3N8/edit#gid=895161300)
